language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

jobs:
  include:
    - stage: test
      install:
        - composer install
      before_script:
        - vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
      script:
        - scripts/phpcodesniffer.sh
    - stage: deploy
      script:
        - scripts/deploy-wp-plugin.sh
